spring:
  application:
    name: nochigima
  config:
    import:
      file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}:${DATABASE_PORT}/nochigima
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

auth:
  jwt:
    secret: ${JWT_SECRET}
  oauth2:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      auth-uri: https://kauth.kakao.com/oauth/authorize
      redirect-uri: ${SERVER_ADDRESS}/v1/auth/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token
      info-uri: https://kapi.kakao.com/v2/user/me
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      auth-uri: https://accounts.google.com/o/oauth2/v2/auth
      redirect-uri: ${SERVER_ADDRESS}/v1/auth/google/callback
      token-uri: https://www.googleapis.com/oauth2/v4/token
      info-uri: https://www.googleapis.com/oauth2/v3/userinfo

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /
    enabled: true
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    persist-authorization: true
