name: JAR 빌드 및 EC2 배포

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: 소스코드 로딩
        uses: actions/checkout@v5

      - name: JDK 설정
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Gradle 캐싱
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradlew 실행권한 부여
        run: chmod +x ./gradlew

      - name: Spotless 포매팅 검사
        run: ./gradlew spotlessCheck

      - name: JAR 빌드
        run: ./gradlew build -x spotlessCheck

      - name: 빌드된 JAR 파일을 EC2로 전송
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_KEY }}
          username: ubuntu
          source: "build/libs/*.jar"
          target: "/home/ubuntu/application"
          strip_components: 2

      - name: EC2에서 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_KEY }}
          username: ubuntu
          script: /home/ubuntu/deploy.sh > /home/ubuntu/logs/deploy.log
